POST http://localhost:3333/api/url
Content-Type: application/json

{
  "code": "google",
  "url": "https://google.com.br"
}


###

GET http://localhost:3333/api/url

###

GET http://localhost:3333/google

###

GET http://localhost:3333/api/metrics